### ISSUE TITLE
I'd like to join!

### ISSUE THREAD

**Issue by HyflerSD** [Dssdiego/elixir_engine#1]
Hey!, I'm an intern C++ developer and I'd like to help you build this project. If you need help with anything a nooby like me can do please let me know and i'll help where I can as i improve my skills

**Comment by Dssdiego** [comment]
Hey @HyflerSD! That's very kind of you!

Well, everybody needs to start from somewhere, right? 😅

If you are new to vulkan, I'd recommend you first start here:

https://vulkan-tutorial.com/
https://vkguide.dev/

Those are really great resources to learn vulkan

But if you already know vulkan, basically what I'm doing with the engine at the moment is restructuring it to separate the vulkan context in "components" such as device, swapchain, pipeline, etc. This will allow me to create a more complex application and enable me to create different kinds of "render systems" 😁

The engine is lacking a lot of stuff right now but every pull request is welcome!

I'll try to describe in the issues some kind of Roadmap in the following days 😉

Thanks again for the interest in the engine 😀

**Comment by HyflerSD** [comment]
Awesome! I'll check those links out soon as i can. And lol i'm a big rookie but so was Michael Jordan at one point (not saying I'm anywhere near his level haha)
